spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: '*'

goofy:
  master:
    datasource:
      url: jdbc:mysql://localhost:3306/goofy?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
      username: root
      password:
      hikari:
        minimum-idle: 5
        maximum-pool-size: 10
  jpa:
    properties:
      hibernate.hbm2ddl.auto: none
  maximum-jdbc-thread-pool-size: 20
